### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by BMaxV** [oargudo/orometry-terrains#2]
Hi, 

This looks like pretty impressive and useful work. I would like to use it for a hopefully commercial project / video game.

But it seems like there is no license, so at the moment, nobody can (legally) use it. 

Whether or not you choose a commercially permissive license or not is up to you of course.

Thanks for the paper / work and examples either way!

**Comment by oargudo** [comment]
Hi,
You're right! We totally forgot to include the license... 
Done! :)

**Comment by BMaxV** [comment]
Wow, that response time! And MIT! Thank you very much!
